//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HealthModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HealthModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.HealthModel", typeof(HealthModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string HealthModelDependenciesHeader {
            get {
                return ResourceManager.GetString("HealthModelDependenciesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health states roll up from resources to the logical components that depend on them..
        /// </summary>
        public static string HealthModelDescription {
            get {
                return ResourceManager.GetString("HealthModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string HealthModelDetailsColumnHeader {
            get {
                return ResourceManager.GetString("HealthModelDetailsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string HealthModelEntityColumnHeader {
            get {
                return ResourceManager.GetString("HealthModelEntityColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health model.
        /// </summary>
        public static string HealthModelHeader {
            get {
                return ResourceManager.GetString("HealthModelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string HealthModelHealthColumnHeader {
            get {
                return ResourceManager.GetString("HealthModelHealthColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entity has no dependencies..
        /// </summary>
        public static string HealthModelNoDependencies {
            get {
                return ResourceManager.GetString("HealthModelNoDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entities in the health model..
        /// </summary>
        public static string HealthModelNoEntities {
            get {
                return ResourceManager.GetString("HealthModelNoEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entity has no signals of its own. Its health comes entirely from its dependencies..
        /// </summary>
        public static string HealthModelNoSignals {
            get {
                return ResourceManager.GetString("HealthModelNoSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} health model.
        /// </summary>
        public static string HealthModelPageTitle {
            get {
                return ResourceManager.GetString("HealthModelPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From dependencies.
        /// </summary>
        public static string HealthModelPropertyDependenciesState {
            get {
                return ResourceManager.GetString("HealthModelPropertyDependenciesState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact.
        /// </summary>
        public static string HealthModelPropertyImpact {
            get {
                return ResourceManager.GetString("HealthModelPropertyImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string HealthModelPropertyResource {
            get {
                return ResourceManager.GetString("HealthModelPropertyResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency rollup.
        /// </summary>
        public static string HealthModelPropertyRollup {
            get {
                return ResourceManager.GetString("HealthModelPropertyRollup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From signals.
        /// </summary>
        public static string HealthModelPropertySignalsState {
            get {
                return ResourceManager.GetString("HealthModelPropertySignalsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollup.
        /// </summary>
        public static string HealthModelRollupColumnHeader {
            get {
                return ResourceManager.GetString("HealthModelRollupColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At most {0} not healthy.
        /// </summary>
        public static string HealthModelRollupMaxNotHealthy {
            get {
                return ResourceManager.GetString("HealthModelRollupMaxNotHealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least {0} healthy.
        /// </summary>
        public static string HealthModelRollupMinHealthy {
            get {
                return ResourceManager.GetString("HealthModelRollupMinHealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst of.
        /// </summary>
        public static string HealthModelRollupWorstOf {
            get {
                return ResourceManager.GetString("HealthModelRollupWorstOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        public static string HealthModelSignalColumnHeader {
            get {
                return ResourceManager.GetString("HealthModelSignalColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} healthy.
        /// </summary>
        public static string HealthModelSignalCount {
            get {
                return ResourceManager.GetString("HealthModelSignalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals.
        /// </summary>
        public static string HealthModelSignalsColumnHeader {
            get {
                return ResourceManager.GetString("HealthModelSignalsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals.
        /// </summary>
        public static string HealthModelSignalsHeader {
            get {
                return ResourceManager.GetString("HealthModelSignalsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string HealthModelStateColumnHeader {
            get {
                return ResourceManager.GetString("HealthModelStateColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string HealthModelTypeColumnHeader {
            get {
                return ResourceManager.GetString("HealthModelTypeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View resource.
        /// </summary>
        public static string HealthModelViewResource {
            get {
                return ResourceManager.GetString("HealthModelViewResource", resourceCulture);
            }
        }
    }
}
